### ISSUE TITLE
Linux voting app selects candidate on mouse move over the whole window

### ISSUE THREAD

**Issue by villuv** [vvk-ehk/ivxv#15]
On candidate selection screen random candidate is selected based on the mouse Y coordinate over the whole window, no clicking needed. Even when moving outside the list area and over the "Valin" button. This makes the application practically unusable.

See video:
https://github.com/valimised/ivxv/assets/497068/45958b07-1429-41d9-82a7-487a51df8ea9

(Arch Linux, KDE5 on xorg)

MD5 of the binary:
4d0d00c59fdaf9e75e1e98dc3239bbe8  EP_2024_linux.bin

**Comment by svenheiberg** [comment]
Hey! Thank you. Proper channel to report errors and get support related to ongoing election is abi@valimised.ee.
