### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by AnnualMedia1328** [vvk-ehk/ivxv#7]
src/ivxv.ee/storage/etcd/etcd.go:15:2: cannot find package "github.com/coreos/etcd/clientv3" in any of:

src/ivxv.ee/storage/etcd/etcd.go:16:2: cannot find package "github.com/coreos/etcd/clientv3/clientv3util" in any of:

src/ivxv.ee/storage/etcd/etcd.go:17:2: cannot find package "github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes" in any of:

src/ivxv.ee/storage/etcd/etcd.go:18:2: cannot find package "google.golang.org/grpc/codes" in any of:

src/ivxv.ee/storage/etcd/etcd.go:19:2: cannot find package "google.golang.org/grpc/status" in any of:

**Comment by duinobot2** [comment]
Hello, did you solve this problem?
