### ISSUE TITLE
.gitmodules missing, also installing modules manually won't fix problem.

### ISSUE THREAD

**Issue by AnnualMedia1328** [vvk-ehk/ivxv#8]
make -C common/java
make[1]: Entering directory '/home/valimised/Töölaud/ivxv/common/java'
/home/valimised/Töölaud/ivxv//common/external/gradle-6.4/bin/gradle build installDist  

BUILD SUCCESSFUL in 599ms
5 actionable tasks: 2 executed, 3 up-to-date
make[1]: Leaving directory '/home/valimised/Töölaud/ivxv/common/java'
make -C key
make[1]: Entering directory '/home/valimised/Töölaud/ivxv/key'
/home/valimised/Töölaud/ivxv//common/external/gradle-6.4/bin/gradle build installDist  

BUILD SUCCESSFUL in 1s
11 actionable tasks: 5 executed, 6 up-to-date
make[1]: Leaving directory '/home/valimised/Töölaud/ivxv/key'
make -C processor
make[1]: Entering directory '/home/valimised/Töölaud/ivxv/processor'
/home/valimised/Töölaud/ivxv//common/external/gradle-6.4/bin/gradle build installDist  

BUILD SUCCESSFUL in 1s
11 actionable tasks: 5 executed, 6 up-to-date
make[1]: Leaving directory '/home/valimised/Töölaud/ivxv/processor'
make -C auditor
make[1]: Entering directory '/home/valimised/Töölaud/ivxv/auditor'
/home/valimised/Töölaud/ivxv//common/external/gradle-6.4/bin/gradle build installDist  

BUILD SUCCESSFUL in 1s
11 actionable tasks: 5 executed, 6 up-to-date
make[1]: Leaving directory '/home/valimised/Töölaud/ivxv/auditor'
make -C common/tools/go
make[1]: Entering directory '/home/valimised/Töölaud/ivxv/common/tools/go'
make -f ../../../common/go/common.mk all
make[2]: Entering directory '/home/valimised/Töölaud/ivxv/common/tools/go'
/usr/lib/go-1.14/bin/go generate ./...
/home/valimised/Töölaud/ivxv/common/tools/go/src/ivxv.ee/cmd/import ./...
env GOBIN=/home/valimised/Töölaud/ivxv/common/tools/go/bin \
	/usr/lib/go-1.14/bin/go install ./...
make[2]: Leaving directory '/home/valimised/Töölaud/ivxv/common/tools/go'
make[1]: Leaving directory '/home/valimised/Töölaud/ivxv/common/tools/go'
make -C common/collector
make[1]: Entering directory '/home/valimised/Töölaud/ivxv/common/collector'
make -f ../go/common.mk all
make[2]: Entering directory '/home/valimised/Töölaud/ivxv/common/collector'
/usr/lib/go-1.14/bin/go generate ./...
/home/valimised/Töölaud/ivxv/common/tools/go/src/ivxv.ee/cmd/import ./...
make -C /home/valimised/Töölaud/ivxv/ common/tools/go
make[3]: Entering directory '/home/valimised/Töölaud/ivxv'
make -C common/tools/go
make[4]: Entering directory '/home/valimised/Töölaud/ivxv/common/tools/go'
make -f ../../../common/go/common.mk all
make[5]: Entering directory '/home/valimised/Töölaud/ivxv/common/tools/go'
/usr/lib/go-1.14/bin/go generate ./...
/home/valimised/Töölaud/ivxv/common/tools/go/src/ivxv.ee/cmd/import ./...
env GOBIN=/home/valimised/Töölaud/ivxv/common/tools/go/bin \
	/usr/lib/go-1.14/bin/go install ./...
make[5]: Leaving directory '/home/valimised/Töölaud/ivxv/common/tools/go'
make[4]: Leaving directory '/home/valimised/Töölaud/ivxv/common/tools/go'
make[3]: Leaving directory '/home/valimised/Töölaud/ivxv'
/home/valimised/Töölaud/ivxv/common/tools/go/bin/gen ./...
env GOBIN=/home/valimised/Töölaud/ivxv/common/collector/bin \
	/usr/lib/go-1.14/bin/go install ./...
src/ivxv.ee/storage/etcd/etcd.go:15:2: found packages clientv3 (auth.go) and main_test (dummy.go) in /usr/lib/go-1.14/src/github.com/coreos/etcd/clientv3
make[2]: *** [../go/common.mk:54: all] Error 1
make[2]: Leaving directory '/home/valimised/Töölaud/ivxv/common/collector'
make[1]: *** [Makefile:20: all] Error 2
make[1]: Leaving directory '/home/valimised/Töölaud/ivxv/common/collector'
make: *** [Makefile:64: common/collector] Error 2

**Comment by Muzosh** [comment]
@svenheiberg I can confirm, the documentation talks about necessary dependencies, that can be installed by `make external`, which points to `git submodule update --init` command. But .gitmodules file is not existent in this repo. I also checked repo history to see, if it existed in the past, but couldn't try to find any trace of it.
